/**
 * Per-profession provisioning specs for LIVE combat tests.
 *
 * Each spec carries the data needed to grant a fully-skilled, fully-geared
 * character for one of the six NGE combat professions:
 *
 *   - `skillChain`: every `class_<prof>_phase{N}_{novice,02..05,master}` skill
 *     in dependency order. `grantSkill` server-side enforces prereqs, so
 *     order matters. Validated against
 *     `~/code/swg-main/dsrc/sku.0/sys.shared/compiled/game/datatables/skill/skills.tab` —
 *     note: NO `_01` variant exists (skips from `_novice` to `_02`).
 *
 *   - `expertise`: every `expertise_<prefix>_*` leaf from
 *     `~/code/swg-main/dsrc/sku.0/sys.shared/compiled/game/datatables/expertise/expertise.tab`.
 *     Sent as ONE `ExpertiseRequestMessage` (god-mode bypasses point limits per
 *     `CreatureObject.cpp:14532`). Order doesn't matter for the wire message.
 *
 *   - `upgradeCommands`: tier-2/3 commands that `recomputeCommandSeries`
 *     doesn't reliably grant after admin XP grants. Granted directly via
 *     `skill grantCommand <cmd> <oid>` (which bypasses the upgrade machinery
 *     per `ConsoleCommandParserSkill.cpp:35`). Names match the highest-tier
 *     ability names from the bundled profession rotation.
 *
 *   - `weaponTemplate`: server template for the primary weapon, classified
 *     to match the bundled rotation's expected `weaponKind`. Spawned into
 *     inventory via `object createIn` and equipped via `transferItemMisc`.
 *
 *   - `npcSpawnTemplate`: default hostile NPC template for the LIVE test. Same
 *     standard humanoid the bot is expected to be able to handle as a level
 *     90 with full equipment. Override via `LIVE_COMBAT_SPAWN_TEMPLATE`.
 *
 *   - `skillTemplate` + `workingSkill` + `legacyProfession`: passed to
 *     `client.fullLifecycle({...})` at character-create time.
 *
 * Composite armor (the 9 chest/leggings/boots/etc. pieces) is shared across
 * every profession — listed separately in `COMPOSITE_ARMOR_TEMPLATES`.
 */

import type { ProfessionId } from '../../src/index.js';

export interface ProfessionProvisioningSpec {
  /** Character-creation NGE skillTemplate (e.g. `'bounty_hunter_1a'`). */
  skillTemplate: string;
  /** Character-creation working skill (e.g. `'class_bountyhunter_phase1_novice'`). */
  workingSkill: string;
  /** Character-creation legacy-profession stub (one of 7 PlayerCreationManager strings). */
  legacyProfession: string;
  /** Skill chain in dependency order. Granted sequentially via `skill grantSkill`. */
  skillChain: readonly string[];
  /** All expertise leaves for this profession. Sent as ONE ExpertiseRequestMessage. */
  expertise: readonly string[];
  /** Tier-2/3 commands granted directly to bypass the broken upgrade pipeline. */
  upgradeCommands: readonly string[];
  /** Weapon template (IFF path). Spawned + equipped at provisioning end. */
  weaponTemplate: string;
  /**
   * Armor pieces to spawn + equip. Empty for Jedi — composite-class armor
   * blocks saber wield (server-side wield permission check). Jedi rely on
   * `centerOfBeing` + `saberBlock` + saber-reflect expertise for defense.
   */
  armorPieces: readonly string[];
  /** Default hostile NPC template for the LIVE test. */
  npcSpawnTemplate: string;
}

/** The 9-slot composite armor set — shared by every combat profession. */
export const COMPOSITE_ARMOR_TEMPLATES: readonly string[] = [
  'object/tangible/wearables/armor/composite/armor_composite_helmet.iff',
  'object/tangible/wearables/armor/composite/armor_composite_chest_plate.iff',
  'object/tangible/wearables/armor/composite/armor_composite_leggings.iff',
  'object/tangible/wearables/armor/composite/armor_composite_boots.iff',
  'object/tangible/wearables/armor/composite/armor_composite_gloves.iff',
  'object/tangible/wearables/armor/composite/armor_composite_bicep_l.iff',
  'object/tangible/wearables/armor/composite/armor_composite_bicep_r.iff',
  'object/tangible/wearables/armor/composite/armor_composite_bracer_l.iff',
  'object/tangible/wearables/armor/composite/armor_composite_bracer_r.iff',
];

/**
 * Build the standard NGE skill chain for a profession. The chain is always
 * 24 skills: novice + 02/03/04/05 + master, repeated for 4 phases. The
 * `_01` variant does NOT exist in this fork — validated against `skills.tab`.
 */
function buildSkillChain(internalName: string): string[] {
  const chain: string[] = [];
  for (let phase = 1; phase <= 4; phase++) {
    chain.push(`class_${internalName}_phase${phase}_novice`);
    for (let level = 2; level <= 5; level++) {
      chain.push(`class_${internalName}_phase${phase}_0${level}`);
    }
    chain.push(`class_${internalName}_phase${phase}_master`);
  }
  return chain;
}

// Expertise lists — extracted verbatim from
// ~/code/swg-main/dsrc/sku.0/sys.shared/compiled/game/datatables/expertise/expertise.tab
// via: grep -E "^expertise_<prefix>_" <expertise.tab> | awk '{print $1}'
// Counts: bh=98, co=106, sp=111, sm=103, of=85, fs=113.

const BH_EXPERTISE: readonly string[] = [
  'expertise_bh_ass_act_1',
  'expertise_bh_ass_act_2',
  'expertise_bh_ass_act_3',
  'expertise_bh_ass_act_4',
  'expertise_bh_ass_dam_1',
  'expertise_bh_ass_dam_2',
  'expertise_bh_ass_dam_3',
  'expertise_bh_ass_cool_1',
  'expertise_bh_ass_cool_2',
  'expertise_bh_innate_1',
  'expertise_bh_return_fire_1',
  'expertise_bh_taunt_1',
  'expertise_bh_fumble_1',
  'expertise_bh_stun_1',
  'expertise_bh_prescience',
  'expertise_bh_absorbtion_1',
  'expertise_bh_absorbtion_2',
  'expertise_bh_absorbtion_3',
  'expertise_bh_absorbtion_4',
  'expertise_bh_deflection_1',
  'expertise_bh_deflection_2',
  'expertise_bh_deflection_3',
  'expertise_bh_deflection_4',
  'expertise_bh_shields_1',
  'expertise_bh_amb_act_1',
  'expertise_bh_amb_act_2',
  'expertise_bh_amb_act_3',
  'expertise_bh_amb_act_4',
  'expertise_bh_amb_dam_1',
  'expertise_bh_amb_dam_2',
  'expertise_bh_amb_dam_3',
  'expertise_bh_amb_cool_1',
  'expertise_bh_amb_cool_2',
  'expertise_bh_surprise_1',
  'expertise_bh_amb_dam_cool',
  'expertise_bh_man_crit_1',
  'expertise_bh_man_crit_2',
  'expertise_bh_man_crit_3',
  'expertise_bh_man_crit_4',
  'expertise_bh_trap_dam_1',
  'expertise_bh_trap_dam_2',
  'expertise_bh_trap_dam_3',
  'expertise_bh_trap_dam_4',
  'expertise_bh_trap_rng_1',
  'expertise_bh_trap_rng_2',
  'expertise_bh_trap_duration_1',
  'expertise_bh_trap_duration_2',
  'expertise_bh_trap_duration_3',
  'expertise_bh_intimidate_1',
  'expertise_bh_dread_strike_1',
  'expertise_bh_stamina_1',
  'expertise_bh_stamina_2',
  'expertise_bh_stamina_3',
  'expertise_bh_stamina_4',
  'expertise_bh_precision_1',
  'expertise_bh_precision_2',
  'expertise_bh_precision_3',
  'expertise_bh_precision_4',
  'expertise_bh_agility_1',
  'expertise_bh_agility_2',
  'expertise_bh_agility_3',
  'expertise_bh_agility_4',
  'expertise_bh_constitution_1',
  'expertise_bh_constitution_2',
  'expertise_bh_constitution_3',
  'expertise_bh_constitution_4',
  'expertise_bh_carbine_act_1',
  'expertise_bh_carbine_act_2',
  'expertise_bh_carbine_act_3',
  'expertise_bh_carbine_act_4',
  'expertise_bh_carbine_dam_1',
  'expertise_bh_carbine_dam_2',
  'expertise_bh_carbine_crit_1',
  'expertise_bh_relentless_1',
  'expertise_bh_rifle_act_1',
  'expertise_bh_rifle_act_2',
  'expertise_bh_rifle_act_3',
  'expertise_bh_rifle_act_4',
  'expertise_bh_rifle_dam_1',
  'expertise_bh_rifle_dam_2',
  'expertise_bh_sniper_1',
  'expertise_bh_cover_1',
  'expertise_bh_armor_kin_1',
  'expertise_bh_armor_kin_2',
  'expertise_bh_armor_kin_3',
  'expertise_bh_armor_kin_4',
  'expertise_bh_armor_mgb_1',
  'expertise_bh_armor_mgb_2',
  'expertise_bh_armor_mgb_3',
  'expertise_bh_armor_sprint_1',
  'expertise_bh_armor_eng_1',
  'expertise_bh_armor_eng_2',
  'expertise_bh_armor_eng_3',
  'expertise_bh_armor_eng_4',
  'expertise_bh_armor_rgb_1',
  'expertise_bh_armor_rgb_2',
  'expertise_bh_armor_rgb_3',
  'expertise_bh_armor_duelist_1',
];

const CO_EXPERTISE: readonly string[] = [
  'expertise_co_remote_detonator_1',
  'expertise_co_powered_armor_1',
  'expertise_co_powered_armor_2',
  'expertise_co_powered_armor_3',
  'expertise_co_powered_armor_4',
  'expertise_co_suppressing_fire_1',
  'expertise_co_cluster_bomb',
  'expertise_co_blow_em_away_1',
  'expertise_co_blow_em_away_2',
  'expertise_co_flashbang_1',
  'expertise_co_flashbang_2',
  'expertise_co_pinpoint_shielding_1',
  'expertise_co_pinpoint_shielding_2',
  'expertise_co_pinpoint_shielding_3',
  'expertise_co_pinpoint_shielding_4',
  'expertise_co_suppression_efficiency_1',
  'expertise_co_suppression_efficiency_2',
  'expertise_co_suppression_efficiency_3',
  'expertise_co_suppression_efficiency_4',
  'expertise_co_killing_spree',
  'expertise_co_killing_grimace_1',
  'expertise_co_killing_grimace_2',
  'expertise_co_timer_reset_1',
  'expertise_co_timer_reset_2',
  'expertise_co_deflective_armor_1',
  'expertise_co_deflective_armor_2',
  'expertise_co_deflective_armor_3',
  'expertise_co_deflective_armor_4',
  'expertise_co_riddle_armor_1',
  'expertise_co_imp_riddle_armor_1',
  'expertise_co_imp_riddle_armor_2',
  'expertise_co_youll_regret_that_1',
  'expertise_co_youll_regret_that_2',
  'expertise_co_youll_regret_that_3',
  'expertise_co_youll_regret_that_4',
  'expertise_co_angled_shrapnel_1',
  'expertise_co_angled_shrapnel_2',
  'expertise_co_blast_resistance_1',
  'expertise_co_blast_resistance_2',
  'expertise_co_blast_resistance_3',
  'expertise_co_blast_resistance_4',
  'expertise_co_armor_cracker_1',
  'expertise_co_stim_armor_1',
  'expertise_co_improved_explosives_1',
  'expertise_co_improved_explosives_2',
  'expertise_co_improved_explosives_3',
  'expertise_co_improved_explosives_4',
  'expertise_co_stand_fast_1',
  'expertise_co_imp_stand_fast_1',
  'expertise_co_imp_stand_fast_2',
  'expertise_co_imp_stand_fast_3',
  'expertise_co_mirror_armor_1',
  'expertise_co_diagnostic_armor_1',
  'expertise_co_general_enhanced_luck_1',
  'expertise_co_general_enhanced_luck_2',
  'expertise_co_enhanced_precision_1',
  'expertise_co_enhanced_precision_2',
  'expertise_co_enhanced_constitution_1',
  'expertise_co_enhanced_constitution_2',
  'expertise_co_enhanced_stamina_1',
  'expertise_co_enhanced_stamina_2',
  'expertise_co_position_secured_1',
  'expertise_co_imp_position_secured_1',
  'expertise_co_imp_position_secured_2',
  'expertise_co_imp_position_secured_3',
  'expertise_co_hose_down_1',
  'expertise_co_hose_down_2',
  'expertise_co_blast_radius_1',
  'expertise_co_blast_radius_2',
  'expertise_co_blast_radius_3',
  'expertise_co_blast_radius_4',
  'expertise_co_focus_beam_1',
  'expertise_co_burst_fire_1',
  'expertise_co_burst_fire_2',
  'expertise_co_keen_eye_1',
  'expertise_co_keen_eye_2',
  'expertise_co_strong_arm_1',
  'expertise_co_strong_arm_2',
  'expertise_co_strong_arm_3',
  'expertise_co_strong_arm_4',
  'expertise_co_tibanna_gas_1',
  'expertise_co_tibanna_gas_2',
  'expertise_co_tibanna_gas_3',
  'expertise_co_tibanna_gas_4',
  'expertise_co_on_target_1',
  'expertise_co_on_target_2',
  'expertise_co_on_target_3',
  'expertise_co_on_target_4',
  'expertise_co_heavy_ammunition_1',
  'expertise_co_heavy_ammunition_2',
  'expertise_co_heavy_ammunition_3',
  'expertise_co_heavy_ammunition_4',
  'expertise_co_packed_explosives_1',
  'expertise_co_packed_explosives_2',
  'expertise_co_packed_explosives_3',
  'expertise_co_packed_explosives_4',
  'expertise_co_lethal_beam_1',
  'expertise_co_base_of_operations_1',
  'expertise_co_marksman_1',
  'expertise_co_marksman_2',
  'expertise_co_marksman_3',
  'expertise_co_short_fuse_1',
  'expertise_co_enhanced_fuel_cans_1',
  'expertise_co_enhanced_fuel_cans_2',
  'expertise_co_enhanced_fuel_cans_3',
  'expertise_co_enhanced_fuel_cans_4',
];

const SP_EXPERTISE: readonly string[] = [
  'expertise_sp_precision_1',
  'expertise_sp_precision_2',
  'expertise_sp_increased_strength_1',
  'expertise_sp_increased_strength_2',
  'expertise_sp_increased_agility_1',
  'expertise_sp_increased_agility_2',
  'expertise_sp_cloaking_armor_1',
  'expertise_sp_cloaking_armor_2',
  'expertise_sp_hidden_daggers_1',
  'expertise_sp_hidden_daggers_2',
  'expertise_sp_cheap_strikes_1',
  'expertise_sp_cheap_strikes_2',
  'expertise_sp_cheap_strikes_3',
  'expertise_sp_cheap_strikes_4',
  'expertise_sp_cheap_shots_1',
  'expertise_sp_cheap_shots_2',
  'expertise_sp_cheap_shots_3',
  'expertise_sp_cheap_shots_4',
  'expertise_sp_protective_armor_1',
  'expertise_sp_protective_armor_2',
  'expertise_sp_protective_armor_3',
  'expertise_sp_protective_armor_4',
  'expertise_sp_improved_spys_fang_1',
  'expertise_sp_opportunity_1',
  'expertise_sp_opportunity_2',
  'expertise_sp_opportunity_3',
  'expertise_sp_opportunity_4',
  'expertise_sp_glancing_armor_1',
  'expertise_sp_glancing_armor_2',
  'expertise_sp_equilibrium',
  'expertise_sp_close_quarters_1',
  'expertise_sp_close_quarters_2',
  'expertise_sp_close_quarters_3',
  'expertise_sp_deadly_pistols_1',
  'expertise_sp_deadly_pistols_2',
  'expertise_sp_deadly_pistols_3',
  'expertise_sp_avoid_damage_1',
  'expertise_sp_assassins_mark',
  'expertise_sp_jagged_edge_1',
  'expertise_sp_jagged_edge_2',
  'expertise_sp_jagged_edge_3',
  'expertise_sp_savagery',
  'expertise_sp_preparation_1',
  'expertise_sp_quiet_steps_1',
  'expertise_sp_quiet_steps_2',
  'expertise_sp_run_its_course_1',
  'expertise_sp_improved_first_aid_1',
  'expertise_sp_improved_first_aid_2',
  'expertise_sp_cloaked_recovery_1',
  'expertise_sp_diversion_1',
  'expertise_sp_diversion_2',
  'expertise_sp_reveal_shadows_1',
  'expertise_sp_rapid_concealment_1',
  'expertise_sp_rapid_concealment_2',
  'expertise_sp_rapid_concealment_3',
  'expertise_sp_rapid_concealment_4',
  'expertise_sp_assassins_blade_1',
  'expertise_sp_assassins_blade_2',
  'expertise_sp_assassins_blade_3',
  'expertise_sp_assassins_blade_4',
  'expertise_sp_puncturing_strikes_1',
  'expertise_sp_puncturing_strikes_2',
  'expertise_sp_puncturing_strikes_3',
  'expertise_sp_puncturing_strikes_4',
  'expertise_sp_cloaked_attacks_1',
  'expertise_sp_careful_observation_1',
  'expertise_sp_careful_observation_2',
  'expertise_sp_smoke_mirrors',
  'expertise_sp_vibrogenerator_1',
  'expertise_sp_vibrogenerator_2',
  'expertise_sp_vibrogenerator_3',
  'expertise_sp_crippling_traps_1',
  'expertise_sp_crippling_traps_2',
  'expertise_sp_cloak_and_dagger_1',
  'expertise_sp_cloak_and_dagger_2',
  'expertise_sp_cloak_and_dagger_3',
  'expertise_sp_cloak_and_dagger_4',
  'expertise_sp_expose_shadows_1',
  'expertise_sp_expose_shadows_2',
  'expertise_sp_expose_shadows_3',
  'expertise_sp_expose_shadows_4',
  'expertise_sp_resonance',
  'expertise_sp_burst_of_shadows_1',
  'expertise_sp_initiative_1',
  'expertise_sp_initiative_2',
  'expertise_sp_initiative_3',
  'expertise_sp_initiative_4',
  'expertise_sp_without_a_trace_1',
  'expertise_sp_covert_mastery_1',
  'expertise_sp_shifty_setup_1',
  'expertise_sp_smoke_screen_1',
  'expertise_sp_smoke_screen_2',
  'expertise_sp_smoke_screen_3',
  'expertise_sp_smoke_screen_4',
  'expertise_sp_decoy_1',
  'expertise_sp_noxious_traps_1',
  'expertise_sp_noxious_traps_2',
  'expertise_sp_steup_1',
  'expertise_sp_steup_2',
  'expertise_sp_steup_3',
  'expertise_sp_steup_4',
  'expertise_sp_shadows_embrace_1',
  'expertise_sp_shadows_embrace_2',
  'expertise_sp_shadows_embrace_3',
  'expertise_sp_shadows_embrace_4',
  'expertise_sp_undercover_1',
  'expertise_sp_undercover_2',
  'expertise_sp_undercover_3',
  'expertise_sp_deadly_toxins_1',
  'expertise_sp_deadly_toxins_2',
  'expertise_sp_improved_arachnids_web_1',
];

const SM_EXPERTISE: readonly string[] = [
  'expertise_sm_general_enhanced_precision_1',
  'expertise_sm_general_enhanced_precision_2',
  'expertise_sm_general_hidden_padding_1',
  'expertise_sm_general_hidden_padding_2',
  'expertise_sm_general_gun_oil_1',
  'expertise_sm_general_elbow_grease_1',
  'expertise_sm_general_enhanced_luck_1',
  'expertise_sm_general_enhanced_luck_2',
  'expertise_sm_general_spot_a_sucker_1',
  'expertise_sm_general_hair_trigger_1',
  'expertise_sm_general_hair_trigger_2',
  'expertise_sm_general_hair_trigger_3',
  'expertise_sm_general_hair_trigger_4',
  'expertise_sm_general_switcheroo_1',
  'expertise_sm_general_switcheroo_2',
  'expertise_sm_general_switcheroo_3',
  'expertise_sm_general_switcheroo_4',
  'expertise_sm_general_off_the_cuff_1',
  'expertise_sm_general_meager_fortune_1',
  'expertise_sm_general_meager_fortune_2',
  'expertise_sm_general_lined_pockets_1',
  'expertise_sm_general_lined_pockets_2',
  'expertise_sm_general_precise_bead_1',
  'expertise_sm_general_precise_bead_2',
  'expertise_sm_general_head_crack_1',
  'expertise_sm_general_head_crack_2',
  'expertise_sm_general_double_deal_1',
  'expertise_sm_general_double_deal_2',
  'expertise_sm_general_wretched_fate_1',
  'expertise_sm_general_wretched_fate_2',
  'expertise_sm_general_idiot_proof_plan_1',
  'expertise_sm_general_idiot_proof_plan_2',
  'expertise_sm_general_hammer_fanning_1',
  'expertise_sm_general_hammer_fanning_2',
  'expertise_sm_general_hammer_fanning_3',
  'expertise_sm_general_hammer_fanning_4',
  'expertise_sm_general_one_two_pummel_1',
  'expertise_sm_general_one_two_pummel_2',
  'expertise_sm_general_one_two_pummel_3',
  'expertise_sm_general_one_two_pummel_4',
  'expertise_sm_general_end_of_the_line_1',
  'expertise_sm_general_poor_prospect_1',
  'expertise_sm_general_poor_prospect_2',
  'expertise_sm_general_narrow_escape_1',
  'expertise_sm_general_break_the_deal_1',
  'expertise_sm_general_bad_odds_1',
  'expertise_sm_general_nerf_herder_1',
  'expertise_sm_path_blindside_1',
  'expertise_sm_path_blindside_2',
  'expertise_sm_path_skullduggery_1',
  'expertise_sm_path_eat_dirt_1',
  'expertise_sm_path_eat_dirt_2',
  'expertise_sm_path_easy_money_1',
  'expertise_sm_path_easy_money_2',
  'expertise_sm_path_ploy_1',
  'expertise_sm_path_ploy_2',
  'expertise_sm_path_healthy_profits_1',
  'expertise_sm_path_sleight_of_hand_1',
  'expertise_sm_path_sleight_of_hand_2',
  'expertise_sm_path_impossible_odds_1',
  'expertise_sm_path_loaded_chance_dice_1',
  'expertise_sm_path_loaded_chance_dice_2',
  'expertise_sm_path_feeling_lucky_1',
  'expertise_sm_path_feeling_lucky_2',
  'expertise_sm_path_feeling_lucky_3',
  'expertise_sm_path_feeling_lucky_4',
  'expertise_sm_path_scandal_1',
  'expertise_sm_path_scandal_2',
  'expertise_sm_path_scandal_3',
  'expertise_sm_path_scandal_4',
  'expertise_sm_path_lucky_break_1',
  'expertise_sm_path_lucky_break_2',
  'expertise_sm_path_lucky_break_3',
  'expertise_sm_path_lucky_break_4',
  'expertise_sm_path_smooth_move_1',
  'expertise_sm_path_smooth_move_2',
  'expertise_sm_path_smooth_move_3',
  'expertise_sm_path_smooth_move_4',
  'expertise_sm_path_off_the_books_1',
  'expertise_sm_path_inside_information_1',
  'expertise_sm_path_flying_tackle_1',
  'expertise_sm_path_flying_tackle_2',
  'expertise_sm_path_pistol_whip_1',
  'expertise_sm_path_beat_down_1',
  'expertise_sm_path_beat_down_2',
  'expertise_sm_path_card_up_your_sleeve_1',
  'expertise_sm_path_card_up_your_sleeve_2',
  'expertise_sm_path_card_up_your_sleeve_3',
  'expertise_sm_path_card_up_your_sleeve_4',
  'expertise_sm_path_false_hope_1',
  'expertise_sm_path_under_the_counter_1',
  'expertise_sm_path_under_the_counter_2',
  'expertise_sm_path_blaster_at_your_side_1',
  'expertise_sm_path_blaster_at_your_side_2',
  'expertise_sm_path_quick_fix_1',
  'expertise_sm_path_quick_fix_2',
  'expertise_sm_path_quick_fix_3',
  'expertise_sm_path_quick_fix_4',
  'expertise_sm_path_fake_goods_1',
  'expertise_sm_path_fake_goods_2',
  'expertise_sm_path_best_deal_ever_1',
  'expertise_sm_path_best_deal_ever_2',
  'expertise_sm_path_shoot_first_1',
];

const OF_EXPERTISE: readonly string[] = [
  'expertise_of_group_buff_duration_1',
  'expertise_of_group_buff_duration_2',
  'expertise_of_advanced_tactics_1',
  'expertise_of_focus_fire_1',
  'expertise_of_drillmaster_1',
  'expertise_of_aggro_channel_1',
  'expertise_of_aggro_channel_2',
  'expertise_of_aggro_channel_3',
  'expertise_of_inspiration_1',
  'expertise_of_scatter_1',
  'expertise_of_charge_1',
  'expertise_of_last_words_1',
  'expertise_of_sup_cool_1',
  'expertise_of_sup_cool_2',
  'expertise_of_sup_cool_3',
  'expertise_of_sup_cool_4',
  'expertise_of_medical_sup_1',
  'expertise_of_tactical_sup_1',
  'expertise_of_reinforcements_1',
  'expertise_of_aoe_act_1',
  'expertise_of_aoe_act_2',
  'expertise_of_aoe_act_3',
  'expertise_of_aoe_act_4',
  'expertise_of_aoe_crit_1',
  'expertise_of_aoe_crit_2',
  'expertise_of_aoe_crit_3',
  'expertise_of_aoe_dam_1',
  'expertise_of_aoe_dam_2',
  'expertise_of_firepower_1',
  'expertise_of_firepower_cool_1',
  'expertise_of_firepower_cool_2',
  'expertise_of_firepower_cool_3',
  'expertise_of_sure_act_1',
  'expertise_of_sure_act_2',
  'expertise_of_sure_act_3',
  'expertise_of_sure_act_4',
  'expertise_of_sure_dam_1',
  'expertise_of_sure_dam_2',
  'expertise_of_sure_dam_3',
  'expertise_of_sure_dam_4',
  'expertise_of_paint_dam_1',
  'expertise_of_paint_dam_2',
  'expertise_of_advanced_paint_1',
  'expertise_of_strength_1',
  'expertise_of_strength_2',
  'expertise_of_strength_3',
  'expertise_of_strength_4',
  'expertise_of_precision_1',
  'expertise_of_precision_2',
  'expertise_of_precision_3',
  'expertise_of_precision_4',
  'expertise_of_constitution_1',
  'expertise_of_constitution_2',
  'expertise_of_constitution_3',
  'expertise_of_constitution_4',
  'expertise_of_stamina_1',
  'expertise_of_stamina_2',
  'expertise_of_stamina_3',
  'expertise_of_stamina_4',
  'expertise_of_1h_dam_1',
  'expertise_of_1h_dam_2',
  'expertise_of_1h_dam_3',
  'expertise_of_1h_dam_4',
  'expertise_of_1h_crit_1',
  'expertise_of_1h_crit_2',
  'expertise_of_decapitate_1',
  'expertise_of_vortex_1',
  'expertise_of_pistol_dam_1',
  'expertise_of_pistol_dam_2',
  'expertise_of_pistol_dam_3',
  'expertise_of_pistol_dam_4',
  'expertise_of_pistol_crit_1',
  'expertise_of_pistol_crit_2',
  'expertise_of_dm_1',
  'expertise_of_pistol_bleed',
  'expertise_of_armor_eng_1',
  'expertise_of_armor_eng_2',
  'expertise_of_stimulator_1',
  'expertise_of_heal_dam_1',
  'expertise_of_heal_dam_2',
  'expertise_of_armor_kin_1',
  'expertise_of_armor_kin_2',
  'expertise_of_purge_1',
  'expertise_of_heal_cool_1',
  'expertise_of_heal_cool_2',
];

const FS_EXPERTISE: readonly string[] = [
  'expertise_fs_general_enhanced_strength_1',
  'expertise_fs_general_enhanced_strength_2',
  'expertise_fs_general_enhanced_constitution_1',
  'expertise_fs_general_enhanced_constitution_2',
  'expertise_fs_general_enhanced_agility_1',
  'expertise_fs_general_enhanced_agility_2',
  'expertise_fs_general_enhanced_stamina_1',
  'expertise_fs_general_enhanced_stamina_2',
  'expertise_fs_general_improved_force_throw_1',
  'expertise_fs_general_improved_force_throw_2',
  'expertise_fs_general_alacrity_1',
  'expertise_fs_general_alacrity_2',
  'expertise_fs_general_alacrity_3',
  'expertise_fs_general_alacrity_4',
  'expertise_fs_general_improved_crippling_accuracy_1',
  'expertise_fs_general_improved_crippling_accuracy_2',
  'expertise_fs_general_improved_crippling_accuracy_3',
  'expertise_fs_general_exacting_strikes_1',
  'expertise_fs_general_exacting_strikes_2',
  'expertise_fs_general_exacting_strikes_3',
  'expertise_fs_general_exacting_strikes_4',
  'expertise_fs_general_force_cloak_1',
  'expertise_fs_general_heightened_speed_1',
  'expertise_fs_general_heightened_speed_2',
  'expertise_fs_general_heightened_speed_3',
  'expertise_fs_general_heightened_speed_4',
  'expertise_fs_general_stance_saber_block_1',
  'expertise_fs_general_improved_saber_block_1',
  'expertise_fs_general_improved_saber_block_2',
  'expertise_fs_general_improved_saber_block_3',
  'expertise_fs_general_incisiveness_1',
  'expertise_fs_general_incisiveness_2',
  'expertise_fs_general_incisiveness_3',
  'expertise_fs_general_second_wind_1',
  'expertise_fs_general_second_wind_2',
  'expertise_fs_general_force_shockwave_1',
  'expertise_fs_general_improved_force_shockwave_1',
  'expertise_fs_general_improved_force_shockwave_2',
  'expertise_fs_general_improved_force_shockwave_3',
  'expertise_fs_general_fidelity_1',
  'expertise_fs_general_fidelity_2',
  'expertise_fs_general_improved_force_cloak_1',
  // expertise_fs_general_premonition_{1..4} are SKIPPED — the rows in
  // skills.tab on this server fork have a malformed column layout that
  // segfaults SkillManager::loadSkill (crashes CreatureObject::grantSkill
  // and brings down SwgGameServer). Watch the server log on LIVE runs
  // for new "SkillManager failed to load skill [...]" warnings — any
  // named there should be added to this skip list and removed from above.
  // expertise_fs_general_grace_in_motion_{1..3} also SKIPPED — same
  // SkillManager::loadSkill segfault as premonition; observed on
  // 2026-05-18 during live-combat-jedi smoke test.
  'expertise_fs_path_cautious_nature_1',
  'expertise_fs_path_cautious_nature_2',
  'expertise_fs_path_cautious_nature_3',
  'expertise_fs_path_cautious_nature_4',
  'expertise_fs_path_remorseless_nature_1',
  'expertise_fs_path_remorseless_nature_2',
  'expertise_fs_path_remorseless_nature_3',
  'expertise_fs_path_remorseless_nature_4',
  'expertise_fs_path_saber_shackle_1',
  'expertise_fs_path_saber_shackle_2',
  'expertise_fs_path_saber_shackle_3',
  'expertise_fs_path_saber_shackle_4',
  'expertise_fs_path_riposte_1',
  'expertise_fs_path_riposte_2',
  'expertise_fs_path_perceptive_sentinel_1',
  'expertise_fs_path_perceptive_sentinel_2',
  'expertise_fs_path_perceptive_sentinel_3',
  'expertise_fs_path_perceptive_sentinel_4',
  'expertise_fs_path_brutality_1',
  'expertise_fs_path_brutality_2',
  'expertise_fs_path_brutality_3',
  'expertise_fs_path_brutality_4',
  'expertise_fs_path_ruthless_precision_1',
  'expertise_fs_path_ruthless_precision_2',
  'expertise_fs_path_ruthless_precision_3',
  'expertise_fs_path_ruthless_precision_4',
  'expertise_fs_path_reactive_response_1',
  'expertise_fs_path_reactive_response_2',
  'expertise_fs_path_saber_reflect_1',
  'expertise_fs_path_forsake_fear_1',
  'expertise_fs_path_cloud_minds_1',
  'expertise_fs_path_dark_lightning_1',
  'expertise_fs_path_tempt_hatred_1',
  'expertise_fs_path_tempt_hatred_2',
  'expertise_fs_path_force_choke_1',
  'expertise_fs_path_force_clarity_1',
  'expertise_fs_path_improved_saber_reflect_1',
  'expertise_fs_path_improved_saber_reflect_2',
  'expertise_fs_path_hermetic_touch_1',
  'expertise_fs_path_expansive_trickery_1',
  'expertise_fs_path_maelstrom_1',
  'expertise_fs_path_force_drain_1',
  'expertise_fs_path_improved_force_choke_1',
  'expertise_fs_path_improved_force_choke_2',
  'expertise_fs_path_anticipate_aggression_1',
  'expertise_fs_path_anticipate_aggression_2',
  'expertise_fs_path_flurry',
  'expertise_fs_path_soothing_aura_1',
  'expertise_fs_path_soothing_aura_2',
  'expertise_fs_path_soothing_aura_3',
  'expertise_fs_path_soothing_aura_4',
  'expertise_fs_path_lethargy_1',
  'expertise_fs_path_lethargy_2',
  'expertise_fs_path_lethargy_3',
  'expertise_fs_path_lethargy_4',
  'expertise_fs_path_wracking_energy_1',
  'expertise_fs_path_wracking_energy_2',
  'expertise_fs_path_wracking_energy_3',
  'expertise_fs_path_wracking_energy_4',
  'expertise_fs_path_improved_force_drain_1',
  'expertise_fs_path_improved_force_drain_2',
  'expertise_fs_path_improved_force_drain_3',
  'expertise_fs_path_strangulation_1',
  'expertise_fs_path_strangulation_2',
];

/**
 * Tier-2/3 commands granted directly via `skill grantCommand <cmd> <oid>`
 * (bypasses the unreliable `recomputeCommandSeries` upgrade pipeline). Names
 * match the highest-tier abilities each profession's bundled rotation
 * (`src/client/script/combat/profession/*.ts`) tries to fire.
 */
const UPGRADE_COMMANDS: Record<ProfessionId, readonly string[]> = {
  bounty_hunter: [
    'bh_dread_strike_5',
    'bh_dm_crit_8',
    'bh_dm_cc_3',
    'bh_del_dm_cc_dot_3',
    'bh_intimidate_6',
    'bh_fumble_6',
    'bh_stun_5',
    'bh_dm_8',
    'bh_flawless_strike',
    'bh_armor_duelist_5',
    'bh_sh_3',
    'bh_shields_1',
  ],
  commando: [
    'co_armor_cracker',
    'co_hw_dm_crit_6',
    'co_hw_dm_6',
    'co_dm_8',
    'co_del_ae_dm_3',
    'co_del_ae_cc_2_2',
    'co_shock_grenade_4',
    'co_ae_dm_3',
    'co_cluster_bomb',
    'co_remote_detonator_5',
    'co_sh_3',
    'co_stand_fast',
    'co_stim_armor',
    'co_killing_spree',
    'co_mirror_armor',
  ],
  spy: [
    'sp_buff_stealth_4',
    'sp_shifty_setup',
    'sp_assassins_mark',
    'sp_hd_range_6',
    'sp_hd_melee_6',
    'sp_dot_5',
    'sp_improved_cc_dot_3',
    'sp_fldmot_3_snare',
    'sp_fld_debuff_ca',
    'sp_dm_8',
    'sp_cc_dot_reac',
    'sp_sh_3',
    'sp_buff_invis_3',
    'sp_run_its_course',
  ],
  smuggler: [
    'sm_shoot_first_5',
    'sm_off_the_cuff',
    'sm_impossible_odds',
    'sm_skullduggery',
    'sm_spot_a_sucker_4',
    'sm_break_the_deal',
    'sm_pistol_whip_4',
    'sm_ae_cover_fire',
    'sm_del_dm_cc_6',
    'sm_dm_cc_6',
    'sm_dm_dot_4',
    'sm_dm_7',
    'sm_sh_3',
    'sm_narrow_escape_4',
    'sm_how_are_you',
  ],
  officer: [
    'of_buff_def_9',
    'of_focus_fire_6',
    'of_inspiration_6',
    'of_deb_def_8',
    'of_deadeye_debuff',
    'of_decapitate_6',
    'of_vortex_5',
    'of_leg_strike_7',
    'of_ae_dm_cc_3',
    'of_del_ae_dm_3',
    'of_del_ae_dm_dot_3',
    'of_dm_8',
    'of_pistol_bleed',
    'of_pistol_dm',
    'of_sh_3',
    'of_emergency_shield',
    'of_purge_1',
  ],
  jedi: [
    'fs_buff_ca_6',
    'fs_saber_reflect_buff',
    'fs_mind_trick_2',
    'fs_flurry_7',
    'fs_dm_cc_crit_5',
    'fs_dm_cc_6_root',
    'fs_maelstrom_5',
    'fs_ae_dm_cc_6',
    'fs_sweep_7',
    'fs_dm_7',
    'fs_sh_3',
    'fs_hermetic_touch',
    'fs_buff_invis_1',
    // Lightsaber wield certification. Granted by the legacy `jedi_padawan_novice`
    // skill (skills.tab) — NOT by the NGE `class_forcesensitive_*` chain — so
    // without it the server's weapon-equip cert check rejects the saber.
    // Certs are commands (they live in the COMMANDS column of skills.tab),
    // so `skill grantCommand` can grant them directly.
    'cert_onehandlightsaber',
    'cert_onehandlightsaber_training',
  ],
};

/**
 * Default NPC spawn templates per profession. All low-to-mid level humanoid
 * creatures that exist on every standard Tatooine/Naboo cluster. Override
 * via the `LIVE_COMBAT_SPAWN_TEMPLATE` env var.
 */
// Starting with `kreetle` — a small low-level naboo insect. Real leveled
// hostile AI (unlike `tusken_raider` which spawns at level -1 on this
// fork and never counter-attacks). Ramp up difficulty via
// LIVE_COMBAT_SPAWN_TEMPLATE once the basic flow is validated.
const DEFAULT_NPC_TEMPLATES: Record<ProfessionId, string> = {
  bounty_hunter: 'object/mobile/kreetle.iff',
  commando: 'object/mobile/kreetle.iff',
  spy: 'object/mobile/kreetle.iff',
  smuggler: 'object/mobile/kreetle.iff',
  officer: 'object/mobile/kreetle.iff',
  jedi: 'object/mobile/kreetle.iff',
};

export const PROVISIONING_SPECS: Record<ProfessionId, ProfessionProvisioningSpec> = {
  bounty_hunter: {
    skillTemplate: 'bounty_hunter_1a',
    workingSkill: 'class_bountyhunter_phase1_novice',
    legacyProfession: 'combat_marksman',
    skillChain: buildSkillChain('bountyhunter'),
    expertise: BH_EXPERTISE,
    upgradeCommands: UPGRADE_COMMANDS.bounty_hunter,
    weaponTemplate: 'object/weapon/ranged/rifle/rifle_t21.iff',
    armorPieces: COMPOSITE_ARMOR_TEMPLATES,
    npcSpawnTemplate: DEFAULT_NPC_TEMPLATES.bounty_hunter,
  },
  commando: {
    skillTemplate: 'commando_1a',
    workingSkill: 'class_commando_phase1_novice',
    legacyProfession: 'combat_brawler',
    skillChain: buildSkillChain('commando'),
    expertise: CO_EXPERTISE,
    upgradeCommands: UPGRADE_COMMANDS.commando,
    weaponTemplate: 'object/weapon/ranged/heavy/heavy_acid_beam.iff',
    armorPieces: COMPOSITE_ARMOR_TEMPLATES,
    npcSpawnTemplate: DEFAULT_NPC_TEMPLATES.commando,
  },
  spy: {
    skillTemplate: 'spy_1a',
    workingSkill: 'class_spy_phase1_novice',
    legacyProfession: 'combat_brawler',
    skillChain: buildSkillChain('spy'),
    expertise: SP_EXPERTISE,
    upgradeCommands: UPGRADE_COMMANDS.spy,
    weaponTemplate: 'object/weapon/melee/knife/knife_dagger.iff',
    armorPieces: COMPOSITE_ARMOR_TEMPLATES,
    npcSpawnTemplate: DEFAULT_NPC_TEMPLATES.spy,
  },
  smuggler: {
    skillTemplate: 'smuggler_1a',
    workingSkill: 'class_smuggler_phase1_novice',
    legacyProfession: 'combat_brawler',
    skillChain: buildSkillChain('smuggler'),
    expertise: SM_EXPERTISE,
    upgradeCommands: UPGRADE_COMMANDS.smuggler,
    weaponTemplate: 'object/weapon/ranged/pistol/pistol_de_10.iff',
    armorPieces: COMPOSITE_ARMOR_TEMPLATES,
    npcSpawnTemplate: DEFAULT_NPC_TEMPLATES.smuggler,
  },
  officer: {
    skillTemplate: 'officer_1a',
    workingSkill: 'class_officer_phase1_novice',
    legacyProfession: 'combat_brawler',
    skillChain: buildSkillChain('officer'),
    expertise: OF_EXPERTISE,
    upgradeCommands: UPGRADE_COMMANDS.officer,
    weaponTemplate: 'object/weapon/ranged/pistol/pistol_de_10.iff',
    armorPieces: COMPOSITE_ARMOR_TEMPLATES,
    npcSpawnTemplate: DEFAULT_NPC_TEMPLATES.officer,
  },
  jedi: {
    skillTemplate: 'force_sensitive_1a',
    workingSkill: 'class_forcesensitive_phase1_novice',
    legacyProfession: 'jedi',
    skillChain: buildSkillChain('forcesensitive'),
    expertise: FS_EXPERTISE,
    upgradeCommands: UPGRADE_COMMANDS.jedi,
    // CRAFTED saber template — uses default_lightsaber.iff slot descriptor
    // (slot 0 = saber_inv, slot 1 = crafted_components). Pre-existing
    // "premium" sabers like shared_sword_lightsaber_dugald.iff use
    // default_weapon.iff and have NO saber_inv slot.
    weaponTemplate: 'object/weapon/melee/sword/crafted_saber/sword_lightsaber_one_handed_gen4.iff',
    // Jedi can't wear conventional armor — the wield-saber permission
    // check fails when composite/anything-but-jedi-robe is equipped.
    // Force-sensitives rely on centerOfBeing + saberBlock + saber-reflect
    // expertise for defense.
    armorPieces: [],
    npcSpawnTemplate: DEFAULT_NPC_TEMPLATES.jedi,
  },
};
